ALTER TYPE "AsaasIntegrationJobType" ADD VALUE IF NOT EXISTS 'PAYMENT_UPDATE_COMMAND';
ALTER TYPE "AsaasIntegrationJobType" ADD VALUE IF NOT EXISTS 'PAYMENT_CANCEL_COMMAND';
ALTER TYPE "AsaasIntegrationJobType" ADD VALUE IF NOT EXISTS 'PAYMENT_REFUND_COMMAND';
ALTER TYPE "AsaasIntegrationJobType" ADD VALUE IF NOT EXISTS 'PAYMENT_UNDO_CASH_COMMAND';
ALTER TYPE "AsaasIntegrationJobType" ADD VALUE IF NOT EXISTS 'PAYMENT_MARK_CASH_COMMAND';
