import { useCallback, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeftIcon, BellAlertIcon, ChatBubbleLeftRightIcon, EnvelopeIcon, PhoneIcon } from 'react-native-heroicons/outline';

import { ErrorState } from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/feedback/Skeleton';
import { SelectField } from '@/components/forms/SelectField';
import { Screen } from '@/components/layout/Screen';
import { AppText } from '@/components/primitives/AppText';
import { Button } from '@/components/primitives/Button';
import { responsibleService } from '@/features/responsibles/services/responsible-service';
import type { StudentNotificationPreference, StudentNotifications } from '@/features/students/types/student';
import { colors, radius, spacing } from '@/theme/tokens';

const scheduleOptions = [0, 1, 3, 5, 7, 10, 15, 30].map((days) => ({ value: String(days), label: days === 0 ? 'No momento adequado' : `${days} ${days === 1 ? 'dia' : 'dias'} antes` }));
const sections = [{ key: 'before', title: 'Antes do vencimento', events: ['PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DUEDATE_WARNING', 'SEND_LINHA_DIGITAVEL'] }, { key: 'overdue', title: 'Cobranças vencidas', events: ['PAYMENT_OVERDUE'] }, { key: 'paid', title: 'Cobranças pagas', events: ['PAYMENT_RECEIVED'] }] as const;

export default function ResponsibleNotificationsScreen() {
  const { responsibleId } = useLocalSearchParams<{ responsibleId?: string }>();
  const [data, setData] = useState<StudentNotifications | null>(null);
  const [preferences, setPreferences] = useState<StudentNotificationPreference[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({ before: true, overdue: true, paid: true });
  const load = useCallback(async () => { if (!responsibleId) { setError('Responsável não encontrado.'); setLoading(false); return; } setLoading(true); setError(null); try { const response = await responsibleService.getNotifications(responsibleId); setData(response); setPreferences(response.preferences); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Não foi possível carregar os avisos.'); } finally { setLoading(false); } }, [responsibleId]);
  useEffect(() => { void load(); }, [load]);
  const changed = useMemo(() => JSON.stringify(preferences) !== JSON.stringify(data?.preferences ?? []), [data?.preferences, preferences]);
  function update(id: string, change: Partial<StudentNotificationPreference>) { setPreferences((current) => current.map((preference) => preference.id === id ? { ...preference, ...change } : preference)); }
  async function save() { if (!responsibleId || saving || !changed || !preferences.length) return; setSaving(true); try { const response = await responsibleService.updateNotifications(responsibleId, preferences); setData(response); setPreferences(response.preferences); Alert.alert('Avisos atualizados', 'As novas preferências foram salvas para este responsável.'); } catch (saveError) { Alert.alert('Não foi possível salvar', saveError instanceof Error ? saveError.message : 'Tente novamente.'); } finally { setSaving(false); } }
  return <Screen scroll backgroundColor={colors.surface} style={styles.screen}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Voltar para detalhes do responsável" hitSlop={10} onPress={() => router.back()} style={styles.headerButton}><ArrowLeftIcon color={colors.ink} size={25} strokeWidth={1.8} /></Pressable><AppText variant="heading" weight="medium">Avisos do responsável</AppText><View style={styles.headerSpacer} /></View><View style={styles.intro}><View style={styles.introIcon}><BellAlertIcon color={colors.brand} size={24} strokeWidth={1.8} /></View><View style={styles.flexCopy}><AppText variant="subheading" weight="medium">Configurações de avisos</AppText><AppText variant="small" tone="muted">Escolha quando e por quais canais o responsável deve receber cada aviso.</AppText></View></View>{loading ? <NotificationSkeleton /> : null}{!loading && error ? <ErrorState title="Não foi possível carregar" message={error} actionLabel="Tentar novamente" onAction={() => void load()} /> : null}{!loading && !error && data?.source === 'unavailable' ? <View style={styles.emptyCard}><AppText weight="medium">Avisos ainda não disponíveis</AppText><AppText variant="small" tone="muted">Este responsável ainda não possui um contato financeiro configurado para receber avisos.</AppText></View> : null}{!loading && !error && preferences.length > 0 ? <View style={styles.groups}>{sections.map((section) => { const rows = preferences.filter((preference) => section.events.includes(preference.event as never)); if (!rows.length) return null; const open = openSections[section.key] ?? true; return <View key={section.key} style={styles.group}><Pressable accessibilityRole="button" accessibilityLabel={`${open ? 'Recolher' : 'Expandir'} ${section.title}`} onPress={() => setOpenSections((current) => ({ ...current, [section.key]: !open }))} style={styles.groupHeader}><AppText variant="subheading" weight="medium" style={styles.flexCopy}>{section.title}</AppText><AppText variant="small" tone="muted">{rows.filter((row) => row.enabled).length}/{rows.length} ativos</AppText></Pressable>{open ? rows.map((preference) => <NotificationRow key={preference.id} preference={preference} onChange={(change) => update(preference.id, change)} />) : null}</View>; })}</View> : null}{!loading && !error && preferences.length > 0 ? <Button title="Salvar alterações" loading={saving} disabled={!changed} onPress={() => void save()} /> : null}</Screen>;
}

function NotificationRow({ preference, onChange }: { preference: StudentNotificationPreference; onChange: (_nextChange: Partial<StudentNotificationPreference>) => void }) { const overdue = preference.event === 'PAYMENT_OVERDUE'; const options = overdue ? scheduleOptions.map((option) => ({ ...option, label: Number(option.value) === 0 ? 'Assim que houver atraso' : `${option.value} ${option.value === '1' ? 'dia' : 'dias'} após o vencimento` })) : scheduleOptions; return <View style={styles.notificationCard}><View style={styles.rowTop}><View style={styles.flexCopy}><AppText weight="medium">{notificationTitle(preference.event)}</AppText><AppText variant="small" tone="muted">{preference.enabled ? 'Escolha os canais de comunicação para este aviso.' : 'Este aviso está desativado.'}</AppText></View><Pressable accessibilityRole="switch" accessibilityLabel={`Ativar ${notificationTitle(preference.event)}`} accessibilityState={{ checked: preference.enabled }} onPress={() => onChange({ enabled: !preference.enabled })} style={[styles.switch, preference.enabled ? styles.switchOn : null]}><View style={[styles.switchThumb, preference.enabled ? styles.switchThumbOn : null]} /></Pressable></View>{preference.enabled ? <><AppText variant="label" weight="medium" tone="muted">Canais para o responsável</AppText><View style={styles.channels}><ChannelButton active={preference.whatsappEnabledForCustomer} label="WhatsApp" onPress={() => onChange({ whatsappEnabledForCustomer: !preference.whatsappEnabledForCustomer })} icon={<ChatBubbleLeftRightIcon color={preference.whatsappEnabledForCustomer ? colors.brand : colors.inkMuted} size={19} />} /><ChannelButton active={preference.emailEnabledForCustomer} label="E-mail" onPress={() => onChange({ emailEnabledForCustomer: !preference.emailEnabledForCustomer })} icon={<EnvelopeIcon color={preference.emailEnabledForCustomer ? colors.brand : colors.inkMuted} size={19} />} /><ChannelButton active={preference.smsEnabledForCustomer} label="SMS" onPress={() => onChange({ smsEnabledForCustomer: !preference.smsEnabledForCustomer })} icon={<PhoneIcon color={preference.smsEnabledForCustomer ? colors.brand : colors.inkMuted} size={19} />} /></View>{overdue ? <SelectField label="Quando enviar" value={scheduleLabel(preference)} selectedValue={String(preference.scheduleOffset)} options={options} onValueChange={(value) => onChange({ scheduleOffset: Number(value) })} /> : null}</> : null}</View>; }
function ChannelButton({ active, label, onPress, icon }: { active: boolean; label: string; onPress: () => void; icon: ReactNode }) { return <Pressable accessibilityRole="checkbox" accessibilityLabel={label} accessibilityState={{ checked: active }} onPress={onPress} style={[styles.channelButton, active ? styles.channelButtonActive : null]}><View style={[styles.channelIcon, active ? styles.channelIconActive : null]}>{icon}</View><AppText variant="tiny" weight="medium" style={active ? styles.activeText : styles.inactiveText}>{label}</AppText></Pressable>; }
function NotificationSkeleton() { return <View style={styles.groups} accessibilityLabel="Carregando avisos">{[0, 1, 2].map((item) => <View key={item} style={styles.notificationCard}><Skeleton width="74%" height={20} /><Skeleton width="92%" height={16} /><Skeleton width="55%" height={16} /><View style={styles.channels}><Skeleton width={66} height={52} radius={radius.md} /><Skeleton width={66} height={52} radius={radius.md} /><Skeleton width={66} height={52} radius={radius.md} /></View></View>)}</View>; }
function notificationTitle(event: string) { const labels: Record<string, string> = { PAYMENT_CREATED: 'Nova cobrança criada', PAYMENT_UPDATED: 'Cobrança alterada', PAYMENT_DUEDATE_WARNING: 'Lembrete de vencimento', SEND_LINHA_DIGITAVEL: 'Linha digitável', PAYMENT_OVERDUE: 'Cobrança em atraso', PAYMENT_RECEIVED: 'Pagamento confirmado' }; return labels[event] ?? 'Aviso financeiro'; }
function scheduleLabel(preference: StudentNotificationPreference) { if (preference.event === 'PAYMENT_OVERDUE' && preference.scheduleOffset > 0) return `${preference.scheduleOffset} dias após o vencimento`; return preference.scheduleOffset === 0 ? 'No momento adequado' : `${preference.scheduleOffset} dias antes`; }
const styles = StyleSheet.create({ screen: { gap: spacing.xl, paddingBottom: spacing['2xl'] }, header: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, headerButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, headerSpacer: { flex: 1 }, intro: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surfaceSoft }, introIcon: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.brandSoft }, flexCopy: { flex: 1, minWidth: 0, gap: spacing.xs }, groups: { gap: spacing.lg }, group: { gap: spacing.md }, groupHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.xs }, notificationCard: { gap: spacing.md, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surfaceNeutral }, rowTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, switch: { width: 48, height: 28, justifyContent: 'center', padding: 3, borderRadius: radius.pill, backgroundColor: colors.border }, switchOn: { backgroundColor: colors.brandSoft }, switchThumb: { width: 22, height: 22, borderRadius: radius.pill, backgroundColor: colors.surface, elevation: 2 }, switchThumbOn: { alignSelf: 'flex-end', backgroundColor: colors.brand }, channels: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, channelButton: { minWidth: 66, minHeight: 54, alignItems: 'center', justifyContent: 'center', gap: spacing.xs, paddingHorizontal: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, channelButtonActive: { backgroundColor: colors.brandSoft, borderColor: colors.brandSoft }, channelIcon: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.surfaceNeutral }, channelIconActive: { backgroundColor: colors.surface }, activeText: { color: colors.brand }, inactiveText: { color: colors.inkMuted }, emptyCard: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surfaceNeutral } });
