ALTER TYPE "PlatformBillingWebhookEventStatus" ADD VALUE IF NOT EXISTS 'PENDING' BEFORE 'RECEIVED';
ALTER TYPE "PlatformBillingWebhookEventStatus" ADD VALUE IF NOT EXISTS 'EXHAUSTED' BEFORE 'IGNORED';
