export const GLOBAL_SEARCH_MIN_QUERY_LENGTH = 2;
export const GLOBAL_SEARCH_GROUP_LIMIT = 4;

export const INTERNAL_ENTITY_ROLES = new Set(['ADMIN', 'FINANCEIRO', 'RECEPCAO']);
export const PORTAL_ROLES = new Set(['ALUNO', 'RESPONSAVEL']);