export declare const SCHOOL_EVENT_STATUSES: readonly ["DRAFT", "PLANNING", "ACTIVE", "FINISHED", "CANCELLED", "ARCHIVED"];
export type SchoolEventStatus = (typeof SCHOOL_EVENT_STATUSES)[number];
export declare const SCHOOL_EVENT_TYPES: readonly ["PRESENTATION", "PARTY", "GRADUATION", "TRIP", "WORKSHOP", "MEETING", "CHAMPIONSHIP", "CULTURAL_SHOW", "OTHER"];
export type SchoolEventType = (typeof SCHOOL_EVENT_TYPES)[number];
export declare const EVENT_TICKET_TYPES: readonly ["FULL", "HALF", "PROMOTIONAL", "COMPLIMENTARY", "STUDENT", "GUARDIAN", "GUEST", "OTHER"];
export type EventTicketType = (typeof EVENT_TICKET_TYPES)[number];
export declare const EVENT_TICKET_MODES: readonly ["NONE", "SIMPLE", "NUMBERED_SEATS"];
export type EventTicketMode = (typeof EVENT_TICKET_MODES)[number];
export declare const EVENT_TICKET_LOT_STATUSES: readonly ["DRAFT", "ACTIVE", "SOLD_OUT", "CLOSED", "CANCELLED", "ARCHIVED"];
export type EventTicketLotStatus = (typeof EVENT_TICKET_LOT_STATUSES)[number];
export declare const EVENT_MAP_STATUSES: readonly ["DRAFT", "PUBLISHED", "ARCHIVED"];
export type EventMapStatus = (typeof EVENT_MAP_STATUSES)[number];
export declare const EVENT_MAP_OBJECT_TYPES: readonly ["BOARD", "SECTION", "ROW", "SEAT", "STAGE", "TABLE", "TEXT", "BLOCKED_AREA", "CORRIDOR", "BOOTH", "GENERAL_AREA"];
export type EventMapObjectType = (typeof EVENT_MAP_OBJECT_TYPES)[number];
export declare const EVENT_SEAT_STATUSES: readonly ["AVAILABLE", "HELD", "SOLD", "BLOCKED", "COMPLIMENTARY", "UNAVAILABLE"];
export type EventSeatStatus = (typeof EVENT_SEAT_STATUSES)[number];
export declare const EVENT_TICKET_SALE_STATUSES: readonly ["PENDING", "PAID", "CANCELLED", "REFUNDED", "COMPLIMENTARY"];
export type EventTicketSaleStatus = (typeof EVENT_TICKET_SALE_STATUSES)[number];
export declare const EVENT_PAYMENT_METHODS: readonly ["CASH", "MANUAL_PIX", "EXTERNAL_CARD", "TRANSFER", "COMPLIMENTARY", "OTHER"];
export type EventPaymentMethod = (typeof EVENT_PAYMENT_METHODS)[number];
export declare const EVENT_COSTUME_CATEGORIES: readonly ["CLOTHING", "ACCESSORY", "SHOES", "PROP", "COMPLETE_KIT", "OTHER"];
export type EventCostumeCategory = (typeof EVENT_COSTUME_CATEGORIES)[number];
export declare const EVENT_COSTUME_ASSIGNMENT_STATUSES: readonly ["PENDING", "ORDERED", "RECEIVED", "DELIVERED", "RETURNED", "DAMAGED", "LOST", "CANCELLED"];
export type EventCostumeAssignmentStatus = (typeof EVENT_COSTUME_ASSIGNMENT_STATUSES)[number];
export declare const EVENT_COSTUME_ASSIGNMENT_BILLING_MODES: readonly ["INCLUDED_IN_REGISTRATION_FEE", "SEPARATE_CHARGE", "FREE"];
export type EventCostumeAssignmentBillingMode = (typeof EVENT_COSTUME_ASSIGNMENT_BILLING_MODES)[number];
export declare const EVENT_FINANCIAL_ENTRY_TYPES: readonly ["COST", "REVENUE"];
export type EventFinancialEntryType = (typeof EVENT_FINANCIAL_ENTRY_TYPES)[number];
export declare const EVENT_FINANCIAL_ENTRY_STATUSES: readonly ["EXPECTED", "PENDING", "PAID", "RECEIVED", "CANCELLED", "REFUNDED"];
export type EventFinancialEntryStatus = (typeof EVENT_FINANCIAL_ENTRY_STATUSES)[number];
export declare const EVENT_FINANCIAL_ORIGIN_TYPES: readonly ["MANUAL", "TICKET_SALE", "COSTUME", "COSTUME_ASSIGNMENT"];
export type EventFinancialOriginType = (typeof EVENT_FINANCIAL_ORIGIN_TYPES)[number];
export declare const EVENT_REPORT_TYPES: readonly ["GENERAL", "EVENT", "COMPARATIVE"];
export type EventReportType = (typeof EVENT_REPORT_TYPES)[number];
export declare const EVENT_STATUS_LABELS: Record<SchoolEventStatus, string>;
export declare const EVENT_TYPE_LABELS: Record<SchoolEventType, string>;
export declare const EVENT_TICKET_TYPE_LABELS: Record<EventTicketType, string>;
export declare const EVENT_TICKET_MODE_LABELS: Record<EventTicketMode, string>;
export declare const EVENT_TICKET_LOT_STATUS_LABELS: Record<EventTicketLotStatus, string>;
export declare const EVENT_MAP_STATUS_LABELS: Record<EventMapStatus, string>;
export declare const EVENT_MAP_OBJECT_TYPE_LABELS: Record<EventMapObjectType, string>;
export declare const EVENT_SEAT_STATUS_LABELS: Record<EventSeatStatus, string>;
export declare const EVENT_TICKET_SALE_STATUS_LABELS: Record<EventTicketSaleStatus, string>;
export declare const EVENT_PAYMENT_METHOD_LABELS: Record<EventPaymentMethod, string>;
export declare const EVENT_COSTUME_CATEGORY_LABELS: Record<EventCostumeCategory, string>;
export declare const EVENT_COSTUME_ASSIGNMENT_STATUS_LABELS: Record<EventCostumeAssignmentStatus, string>;
export declare const EVENT_COSTUME_ASSIGNMENT_BILLING_MODE_LABELS: Record<EventCostumeAssignmentBillingMode, string>;
export declare const EVENT_FINANCIAL_STATUS_LABELS: Record<EventFinancialEntryStatus, string>;
export declare const EVENT_COST_CATEGORIES: readonly ["Figurino", "Decoração", "Espaço", "Som e iluminação", "Alimentação", "Transporte", "Equipe", "Material", "Marketing", "Taxas", "Fornecedor", "Outros"];
export declare const EVENT_REVENUE_CATEGORIES: readonly ["Venda de ingresso", "Figurino", "Patrocínio", "Venda interna", "Inscrição", "Taxa extra", "Outros"];
//# sourceMappingURL=types.d.ts.map
